(() => {
  const canvas = document.querySelector('#canvas');
  const ctx = canvas.getContext('2d');
  const fileInput = document.querySelector('#fileInput');
  const list = document.querySelector('#imageList');
  const wrap = document.querySelector('#canvasWrap');
  const welcome = document.querySelector('#welcome');
  const overlay = document.querySelector('#cropOverlay');
  const boundary = overlay.querySelector('.crop-boundary');
  const cropInputs = ['cropX', 'cropY', 'cropWidth', 'cropHeight'].map(id => document.querySelector(`#${id}`));
  const state = { images: [], selected: -1, tool: 'select', color: '#ff4d6d', width: 4, drawing: false, start: null, current: null, preview: null, cropActive: false, selectedAnnotation: null, annotationInteraction: null, clipboard: null };

  const escapeHtml = value => value.replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
  const current = () => state.images[state.selected];
  const cropRect = () => Object.fromEntries(cropInputs.map(input => [input.id.replace('crop', '').toLowerCase(), Number(input.value)]));
  const validRect = (rect, image) => Object.values(rect).every(Number.isFinite) && rect.x >= 0 && rect.y >= 0 && rect.width > 0 && rect.height > 0 && rect.x + rect.width <= image.image.naturalWidth && rect.y + rect.height <= image.image.naturalHeight;
  const setCropStatus = message => { document.querySelector('#cropStatus').textContent = message; };
  const updateDoneButton = () => { const button = document.querySelector('#markDone'); const image = current(); button.disabled = !image; button.textContent = image?.done ? 'Completed' : 'Mark as done'; button.classList.toggle('is-done', !!image?.done); };
  const pointer = event => { const r = canvas.getBoundingClientRect(); return { x: (event.clientX - r.left) * canvas.width / r.width, y: (event.clientY - r.top) * canvas.height / r.height }; };
  const cacheDb = () => new Promise((resolve, reject) => { const request = indexedDB.open('frame-image-cache', 1); request.onupgradeneeded = () => request.result.createObjectStore('images', { keyPath: 'hash' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
  const hashFile = async file => { const bytes = await crypto.subtle.digest('SHA-256', await file.arrayBuffer()); return [...new Uint8Array(bytes)].map(value => value.toString(16).padStart(2, '0')).join(''); };
  const cacheImage = async (hash, file) => { try { const db = await cacheDb(); const transaction = db.transaction('images', 'readwrite'); transaction.objectStore('images').put({ hash, name: file.name, type: file.type, blob: file, savedAt: Date.now() }); } catch (error) { console.warn('Image cache unavailable:', error); } };
  const persistImage = image => { if (!image?.hash) return; clearTimeout(image.persistTimer); image.persistTimer = setTimeout(async () => { try { const db = await cacheDb(); const store = db.transaction('images', 'readwrite').objectStore('images'); const request = store.get(image.hash); request.onsuccess = () => { const record = request.result; if (record) store.put({ ...record, annotations: image.annotations, done: image.done }); }; } catch (error) { console.warn('Could not save annotation state:', error); } }, 120); };
  const restoreCachedImages = async () => { try { const db = await cacheDb(); const records = await new Promise((resolve, reject) => { const request = db.transaction('images').objectStore('images').getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); for (const record of records.sort((a, b) => a.savedAt - b.savedAt)) { const image = new Image(); const url = URL.createObjectURL(record.blob); image.onload = () => { state.images.push({ name: record.name, sourceUrl: url, url, image, hash: record.hash, annotations: record.annotations || [], done: !!record.done }); if (state.selected < 0) select(0); else renderList(); }; image.src = url; } } catch (error) { console.warn('Could not restore cached images:', error); } };
  const hitShape = point => { const annotations = current()?.annotations || []; for (let i = annotations.length - 1; i >= 0; i -= 1) { const item = annotations[i]; if (!['rectangle', 'ellipse', 'arrow'].includes(item.type)) continue; const x = Math.min(item.x, item.x + item.w), y = Math.min(item.y, item.y + item.h), right = Math.max(item.x, item.x + item.w), bottom = Math.max(item.y, item.y + item.h); if (point.x >= x - 8 && point.x <= right + 8 && point.y >= y - 8 && point.y <= bottom + 8) return i; } return null; };
  const renderSelection = () => { const item = current()?.annotations[state.selectedAnnotation]; if (!item || !['rectangle', 'ellipse', 'arrow'].includes(item.type)) return; const x = Math.min(item.x, item.x + item.w), y = Math.min(item.y, item.y + item.h), w = Math.abs(item.w), h = Math.abs(item.h); ctx.save(); ctx.setLineDash([6, 4]); ctx.strokeStyle = '#1785ff'; ctx.lineWidth = 2; ctx.strokeRect(x - 3, y - 3, w + 6, h + 6); ctx.setLineDash([]); ctx.fillStyle = '#1785ff'; [[x, y], [x + w, y + h]].forEach(([handleX, handleY]) => ctx.fillRect(handleX - 5, handleY - 5, 10, 10)); ctx.restore(); };
  const renderAnnotationTo = (target, annotation) => { target.save(); target.lineCap = 'round'; target.lineJoin = 'round'; target.strokeStyle = annotation.color; target.lineWidth = annotation.width; if (annotation.type === 'pen') { target.beginPath(); annotation.points.forEach((point, i) => i ? target.lineTo(point.x, point.y) : target.moveTo(point.x, point.y)); target.stroke(); target.restore(); return; } if (annotation.type === 'text') { target.fillStyle = annotation.color; target.font = `600 ${Math.max(14, annotation.width * 5)}px ui-sans-serif, sans-serif`; target.fillText(annotation.text, annotation.x, annotation.y); target.restore(); return; } target.beginPath(); if (annotation.type === 'rectangle') target.rect(annotation.x, annotation.y, annotation.w, annotation.h); if (annotation.type === 'ellipse') target.ellipse(annotation.x + annotation.w / 2, annotation.y + annotation.h / 2, Math.abs(annotation.w / 2), Math.abs(annotation.h / 2), 0, 0, Math.PI * 2); if (annotation.type === 'arrow') { target.moveTo(annotation.x, annotation.y); target.lineTo(annotation.x + annotation.w, annotation.y + annotation.h); const angle = Math.atan2(annotation.h, annotation.w), size = Math.max(10, annotation.width * 4); target.moveTo(annotation.x + annotation.w, annotation.y + annotation.h); target.lineTo(annotation.x + annotation.w - size * Math.cos(angle - .5), annotation.y + annotation.h - size * Math.sin(angle - .5)); target.moveTo(annotation.x + annotation.w, annotation.y + annotation.h); target.lineTo(annotation.x + annotation.w - size * Math.cos(angle + .5), annotation.y + annotation.h - size * Math.sin(angle + .5)); } target.stroke(); target.restore(); };
  const exportImage = (image, type = 'image/png') => new Promise(resolve => { const output = document.createElement('canvas'); output.width = image.image.naturalWidth; output.height = image.image.naturalHeight; const outputContext = output.getContext('2d'); outputContext.drawImage(image.image, 0, 0); image.annotations.forEach(annotation => renderAnnotationTo(outputContext, annotation)); output.toBlob(resolve, type); });

  const updateCropPreview = () => {
    const image = current();
    document.querySelector('#applyCrop').disabled = !image;
    document.querySelector('#applyCropAll').disabled = !image || state.images.length < 2;
    if (!image || !state.cropActive) { overlay.hidden = true; return; }
    overlay.hidden = false;
    const rect = cropRect();
    const scaleX = canvas.clientWidth / canvas.width;
    const scaleY = canvas.clientHeight / canvas.height;
    boundary.style.left = `${rect.x * scaleX}px`;
    boundary.style.top = `${rect.y * scaleY}px`;
    boundary.style.width = `${Math.max(0, rect.width * scaleX)}px`;
    boundary.style.height = `${Math.max(0, rect.height * scaleY)}px`;
    const valid = validRect(rect, image);
    cropInputs.forEach(input => input.classList.toggle('invalid', !valid));
    setCropStatus(valid ? `${image.image.naturalWidth} × ${image.image.naturalHeight} px image` : 'Crop must fit inside the selected image.');
  };
  const draw = () => {
    const image = current();
    if (!image) return;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(image.image, 0, 0);
    image.annotations.forEach(render);
    if (state.preview) render(state.preview);
    renderSelection();
    document.querySelector('#undo').disabled = !image.annotations.length;
    document.querySelector('#clear').disabled = !image.annotations.length;
    updateCropPreview();
  };
  const fitCanvas = () => { const image = current(); if (!image) return; canvas.width = image.image.naturalWidth; canvas.height = image.image.naturalHeight; draw(); };
  const setup = () => { ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.strokeStyle = state.color; ctx.lineWidth = state.width; };
  const render = annotation => {
    setup(); ctx.strokeStyle = annotation.color; ctx.lineWidth = annotation.width;
    if (annotation.type === 'pen') { ctx.beginPath(); annotation.points.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); return; }
    if (annotation.type === 'text') { ctx.fillStyle = annotation.color; ctx.font = `600 ${Math.max(14, annotation.width * 5)}px ui-sans-serif, sans-serif`; ctx.fillText(annotation.text, annotation.x, annotation.y); return; }
    ctx.beginPath();
    if (annotation.type === 'rectangle') ctx.rect(annotation.x, annotation.y, annotation.w, annotation.h);
    if (annotation.type === 'ellipse') ctx.ellipse(annotation.x + annotation.w / 2, annotation.y + annotation.h / 2, Math.abs(annotation.w / 2), Math.abs(annotation.h / 2), 0, 0, Math.PI * 2);
    if (annotation.type === 'arrow') { ctx.moveTo(annotation.x, annotation.y); ctx.lineTo(annotation.x + annotation.w, annotation.y + annotation.h); const angle = Math.atan2(annotation.h, annotation.w), size = Math.max(10, annotation.width * 4); ctx.moveTo(annotation.x + annotation.w, annotation.y + annotation.h); ctx.lineTo(annotation.x + annotation.w - size * Math.cos(angle - .5), annotation.y + annotation.h - size * Math.sin(angle - .5)); ctx.moveTo(annotation.x + annotation.w, annotation.y + annotation.h); ctx.lineTo(annotation.x + annotation.w - size * Math.cos(angle + .5), annotation.y + annotation.h - size * Math.sin(angle + .5)); }
    ctx.stroke();
  };
  const renderList = () => {
    document.querySelector('#imageCount').textContent = state.images.length;
    if (!state.images.length) { list.innerHTML = '<div class="empty-state"><span>◌</span><p>No images yet</p><small>Upload a screenshot to get started</small></div>'; return; }
    list.innerHTML = state.images.map((item, i) => `<div class="thumb ${i === state.selected ? 'active' : ''}" data-index="${i}"><img src="${item.url}" alt=""><div class="thumb-info"><div><div class="thumb-name">${escapeHtml(item.name)}</div><div class="thumb-meta">${item.image.naturalWidth} × ${item.image.naturalHeight}</div></div>${item.done ? '<span class="completion-badge">Done</span>' : ''}</div></div>`).join('');
    list.querySelectorAll('.thumb').forEach(el => el.addEventListener('click', () => select(Number(el.dataset.index))));
    renderAnnotations();
  };
  const renderAnnotations = () => { const panel = document.querySelector('#annotationPanel'); const listElement = document.querySelector('#annotationList'); const image = current(); if (!image) { panel.hidden = true; return; } panel.hidden = false; document.querySelector('#annotationCount').textContent = image.annotations.length; if (!image.annotations.length) { listElement.innerHTML = '<div class="annotation-empty">Draw a shape to edit it here.</div>'; return; } listElement.innerHTML = image.annotations.map((item, index) => { const label = item.type[0].toUpperCase() + item.type.slice(1); const editable = ['rectangle', 'ellipse', 'arrow'].includes(item.type); return `<details class="annotation-item" data-index="${index}" ${state.selectedAnnotation === index ? 'open' : ''}><summary><span class="annotation-type">${label}</span><span class="annotation-number">#${index + 1}</span></summary>${editable ? `<div class="annotation-fields"><label>X<input data-field="x" type="number" value="${Math.round(item.x)}"></label><label>Y<input data-field="y" type="number" value="${Math.round(item.y)}"></label><label>W<input data-field="w" type="number" value="${Math.round(item.w)}"></label><label>H<input data-field="h" type="number" value="${Math.round(item.h)}"></label><label>Color<input data-field="color" type="color" value="${item.color}"></label><button class="annotation-delete" type="button" data-delete>Delete</button></div>` : '<div class="annotation-fields"><span class="annotation-empty">Use Select to move this annotation.</span><button class="annotation-delete" type="button" data-delete>Delete</button></div>'}</details>`; }).join(''); listElement.querySelectorAll('.annotation-item').forEach(item => { const index = Number(item.dataset.index); item.addEventListener('toggle', () => { if (item.open) { state.selectedAnnotation = index; draw(); } }); item.querySelectorAll('[data-field]').forEach(input => input.addEventListener('input', () => { const annotation = current().annotations[index]; annotation[input.dataset.field] = input.dataset.field === 'color' ? input.value : Number(input.value); state.selectedAnnotation = index; persistImage(current()); draw(); })); item.querySelector('[data-delete]').addEventListener('click', event => { event.preventDefault(); current().annotations.splice(index, 1); state.selectedAnnotation = null; persistImage(current()); draw(); renderAnnotations(); }); }); };
  const select = index => { state.selected = index; state.selectedAnnotation = null; state.annotationInteraction = null; state.preview = null; const image = current(); welcome.hidden = !!image; wrap.hidden = !image; if (image) { document.querySelector('#canvasStatus').textContent = `${image.name} · ${image.image.naturalWidth} × ${image.image.naturalHeight}`; fitCanvas(); } renderList(); updateDoneButton(); };
  const addFiles = async files => { const images = [...files].filter(file => /^image\/(png|jpeg)$/.test(file.type)); for (const file of images) { const hash = await hashFile(file); if (state.images.some(item => item.hash === hash)) continue; await cacheImage(hash, file); const image = new Image(); const url = URL.createObjectURL(file); image.onload = () => { state.images.push({ name: file.name, sourceUrl: url, url, image, hash, annotations: [], done: false }); if (state.selected < 0) select(0); else renderList(); }; image.src = url; } fileInput.value = ''; };
  const translate = (annotation, x, y) => annotation.type === 'pen' ? { ...annotation, points: annotation.points.map(point => ({ x: point.x - x, y: point.y - y })) } : { ...annotation, x: annotation.x - x, y: annotation.y - y };
  const cropImage = (image, rect) => new Promise(resolve => { const output = document.createElement('canvas'); output.width = rect.width; output.height = rect.height; output.getContext('2d').drawImage(image.image, rect.x, rect.y, rect.width, rect.height, 0, 0, rect.width, rect.height); const url = output.toDataURL('image/png'); const cropped = new Image(); cropped.onload = () => resolve({ ...image, image: cropped, url, annotations: image.annotations.map(annotation => translate(annotation, rect.x, rect.y)) }); cropped.src = url; });
  const applyCropTo = async image => { const rect = cropRect(); if (!validRect(rect, image)) return false; const cropped = await cropImage(image, rect); Object.assign(image, cropped); return true; };
  const applyCrop = async all => {
    state.cropActive = true;
    const image = current(); const rect = cropRect();
    if (!image || !validRect(rect, image)) { updateCropPreview(); return; }
    if (all && state.images.some(item => !validRect(rect, item))) { setCropStatus('The crop must fit inside every loaded image.'); return; }
    const targets = all ? state.images : [image];
    for (const target of targets) { await applyCropTo(target); persistImage(target); }
    select(state.selected); setCropStatus(all ? `Crop applied to ${targets.length} images.` : 'Crop applied to the selected image.');
  };
  const reloadOriginal = async () => { const image = current(); if (!image) return; const result = await Swal.fire({ icon: 'warning', title: 'Reload original image?', text: 'Annotations and crop changes on this image will be removed.', showCancelButton: true, confirmButtonText: 'Reload original', confirmButtonColor: '#ff4d6d' }); if (!result.isConfirmed) return; const original = new Image(); original.onload = () => { image.image = original; image.url = image.sourceUrl; image.annotations = []; image.done = false; persistImage(image); select(state.selected); }; original.src = image.sourceUrl; };
  const markDone = async () => { const image = current(); if (!image) return; if (!image.annotations.length) { const result = await Swal.fire({ icon: 'warning', title: 'No annotations added', text: 'There are no annotations on this image. Mark it as complete anyway?', showCancelButton: true, confirmButtonText: 'Mark complete anyway', confirmButtonColor: '#ff4d6d' }); if (!result.isConfirmed) return; } image.done = true; persistImage(image); renderList(); updateDoneButton(); await Swal.fire({ icon: 'success', title: 'Marked as done', text: image.name, timer: 1300, showConfirmButton: false }); };
  const clearQueue = async () => { if (!state.images.length) return; const result = await Swal.fire({ icon: 'warning', title: 'Clear image queue?', text: `Remove all ${state.images.length} loaded images and their local cache?`, showCancelButton: true, confirmButtonText: 'Clear queue', confirmButtonColor: '#c63250' }); if (!result.isConfirmed) return; state.images.forEach(image => URL.revokeObjectURL(image.sourceUrl)); state.images = []; state.selected = -1; state.selectedAnnotation = null; try { const db = await cacheDb(); db.transaction('images', 'readwrite').objectStore('images').clear(); } catch (error) { console.warn('Could not clear image cache:', error); } select(-1); await Swal.fire({ icon: 'success', title: 'Queue cleared', timer: 1000, showConfirmButton: false }); };

  const finish = () => { if (!state.start || !state.current) return; const s = state.start, p = state.current, x = Math.min(s.x, p.x), y = Math.min(s.y, p.y), w = Math.abs(p.x - s.x), h = Math.abs(p.y - s.y); let annotation = { type: state.tool, x, y, w, h, color: state.color, width: state.width }; if (state.tool === 'arrow') annotation = { ...annotation, x: s.x, y: s.y, w: p.x - s.x, h: p.y - s.y }; if (state.tool === 'pen') annotation = { type: 'pen', points: state.preview.points, color: state.color, width: state.width }; if (state.tool === 'pen' ? state.preview.points.length > 0 : w > 2 || h > 2) current().annotations.push(annotation); persistImage(current()); state.drawing = false; state.start = null; state.current = null; state.preview = null; draw(); renderAnnotations(); };
  canvas.addEventListener('pointerdown', async event => { event.preventDefault(); if (!current()) return; const point = pointer(event); if (state.tool === 'select') { const index = hitShape(point); state.selectedAnnotation = index; if (index !== null) { const item = current().annotations[index]; const nearHandle = Math.abs(point.x - (item.x + item.w)) < 14 && Math.abs(point.y - (item.y + item.h)) < 14; state.annotationInteraction = { mode: nearHandle ? 'resize' : 'move', start: point, original: { x: item.x, y: item.y, w: item.w, h: item.h } }; canvas.setPointerCapture(event.pointerId); } draw(); return; } canvas.setPointerCapture(event.pointerId); if (state.tool === 'text') { const result = await Swal.fire({ title: 'Add text annotation', input: 'text', inputPlaceholder: 'Type your annotation', showCancelButton: true, confirmButtonText: 'Add', confirmButtonColor: '#ff4d6d' }); if (result.isConfirmed && result.value) { current().annotations.push({ type: 'text', text: result.value, x: point.x, y: point.y, color: state.color, width: state.width }); persistImage(current()); } draw(); return; } state.drawing = true; state.start = point; state.current = point; state.preview = state.tool === 'pen' ? { type: 'pen', points: [point], color: state.color, width: state.width } : { type: state.tool, x: point.x, y: point.y, w: 0, h: 0, color: state.color, width: state.width }; });
  canvas.addEventListener('pointermove', event => { const point = pointer(event); if (state.annotationInteraction) { const item = current().annotations[state.selectedAnnotation]; const deltaX = point.x - state.annotationInteraction.start.x, deltaY = point.y - state.annotationInteraction.start.y; if (state.annotationInteraction.mode === 'move') { item.x = state.annotationInteraction.original.x + deltaX; item.y = state.annotationInteraction.original.y + deltaY; } else { item.w = Math.max(4, state.annotationInteraction.original.w + deltaX); item.h = Math.max(4, state.annotationInteraction.original.h + deltaY); } draw(); return; } if (!state.drawing) return; state.current = point; if (state.tool === 'pen') state.preview.points.push(point); else { state.preview.x = state.tool === 'arrow' ? state.start.x : Math.min(state.start.x, point.x); state.preview.y = state.tool === 'arrow' ? state.start.y : Math.min(state.start.y, point.y); state.preview.w = state.tool === 'arrow' ? point.x - state.start.x : Math.abs(point.x - state.start.x); state.preview.h = state.tool === 'arrow' ? point.y - state.start.y : Math.abs(point.y - state.start.y); } draw(); });
  canvas.addEventListener('pointerup', event => { if (state.annotationInteraction) { state.annotationInteraction = null; canvas.releasePointerCapture(event.pointerId); persistImage(current()); draw(); renderAnnotations(); return; } finish(); }); canvas.addEventListener('pointercancel', event => { state.annotationInteraction = null; finish(); });
  canvas.addEventListener('dragstart', event => event.preventDefault());
  document.querySelectorAll('[data-tool]').forEach(button => button.addEventListener('click', () => { state.tool = button.dataset.tool; document.querySelectorAll('.tool').forEach(item => item.classList.toggle('active', item === button)); }));
  document.querySelector('#colorInput').addEventListener('input', event => state.color = event.target.value); document.querySelector('#widthInput').addEventListener('input', event => { state.width = +event.target.value; document.querySelector('#widthValue').textContent = `${state.width} px`; });
  cropInputs.forEach(input => input.addEventListener('input', () => { state.cropActive = true; updateCropPreview(); }));
  document.querySelector('#applyCrop').addEventListener('click', () => applyCrop(false)); document.querySelector('#applyCropAll').addEventListener('click', () => applyCrop(true));
  document.querySelector('#undo').addEventListener('click', () => { if (current()?.annotations.length) { current().annotations.pop(); persistImage(current()); draw(); renderAnnotations(); } }); document.querySelector('#clear').addEventListener('click', async () => { if (!current()) return; const result = await Swal.fire({ icon: 'warning', title: 'Clear annotations?', text: 'All annotations on this image will be removed.', showCancelButton: true, confirmButtonText: 'Clear annotations', confirmButtonColor: '#ff4d6d' }); if (result.isConfirmed) { current().annotations = []; state.selectedAnnotation = null; persistImage(current()); draw(); renderAnnotations(); } });
  document.querySelector('#resetImage').addEventListener('click', reloadOriginal); document.querySelector('#markDone').addEventListener('click', markDone); document.querySelector('#clearQueue').addEventListener('click', clearQueue);
  const canvasToBlob = target => new Promise(resolve => target.toBlob(resolve, 'image/png'));
  const triggerDownload = (blob, name) => { const link = document.createElement('a'); link.download = name; link.href = URL.createObjectURL(blob); link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); };
  document.querySelector('#download').addEventListener('click', () => { if (!current()) return; triggerDownload(canvasToBlob(canvas), `${current().name.replace(/\.[^.]+$/, '')}-annotated.png`); });
  document.querySelector('#downloadAll').addEventListener('click', async () => { if (!state.images.length) return; for (const image of state.images) triggerDownload(await exportImage(image), `${image.name.replace(/\.[^.]+$/, '')}-annotated.png`); });
  document.querySelector('#downloadZip').addEventListener('click', async () => { if (!state.images.length) return; if (!window.JSZip) { await Swal.fire({ icon: 'error', title: 'ZIP library unavailable', text: 'Reload the page and try again.' }); return; } const zip = new JSZip(); for (const image of state.images) zip.file(`${image.name.replace(/\.[^.]+$/, '')}-annotated.png`, await exportImage(image)); triggerDownload(await zip.generateAsync({ type: 'blob' }), 'frame-annotations.zip'); });
  fileInput.addEventListener('change', event => addFiles(event.target.files));
  const drop = document.querySelector('#dropZone'); ['dragenter', 'dragover'].forEach(type => drop.addEventListener(type, event => { event.preventDefault(); drop.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(type => drop.addEventListener(type, event => { event.preventDefault(); drop.classList.remove('dragging'); })); drop.addEventListener('drop', event => addFiles(event.dataTransfer.files));
  window.addEventListener('resize', updateCropPreview); document.addEventListener('keydown', event => { const shortcut = event.metaKey || event.ctrlKey; if (shortcut && event.key.toLowerCase() === 'z') { event.preventDefault(); document.querySelector('#undo').click(); } if (shortcut && event.key.toLowerCase() === 's') { event.preventDefault(); document.querySelector('#download').click(); } if (shortcut && event.key.toLowerCase() === 'c' && !event.target.matches('input,textarea')) { const item = current()?.annotations[state.selectedAnnotation]; if (item) { event.preventDefault(); state.clipboard = JSON.parse(JSON.stringify(item)); } } if (shortcut && event.key.toLowerCase() === 'v' && !event.target.matches('input,textarea')) { if (state.clipboard && current()) { event.preventDefault(); const pasted = JSON.parse(JSON.stringify(state.clipboard)); if ('x' in pasted) pasted.x += 20; if ('y' in pasted) pasted.y += 20; if (pasted.type === 'pen') pasted.points = pasted.points.map(point => ({ x: point.x + 20, y: point.y + 20 })); current().annotations.push(pasted); persistImage(current()); state.selectedAnnotation = current().annotations.length - 1; state.tool = 'select'; document.querySelectorAll('.tool').forEach(item => item.classList.toggle('active', item.dataset.tool === 'select')); draw(); } } if (event.target.matches('input,textarea')) return; const tools = { v: 'select', r: 'rectangle', e: 'ellipse', a: 'arrow', p: 'pen', t: 'text' }; if (tools[event.key.toLowerCase()]) document.querySelector(`[data-tool="${tools[event.key.toLowerCase()]}"]`).click(); });
  restoreCachedImages();
})();
